### ISSUE TITLE
README Does not explain usage

### ISSUE THREAD

**Issue by shawnwanderson** [robertbasic/vim-hugo-helper#1]
A few use cases on the readme, or a paragraph explaining how this is useful would be a great addition.

**Comment by FilBot3** [comment]
I want to say that its just the same as a regular Pathogen install, just `cd` to your `vimfiles` directory, and clone the repo, restart VIM, and it should start working.

**Comment by robertbasic** [comment]
Hey!

I've updated the readme file and plan on adding a couple of more helpers, as soon as I figure out the best way to write them to make them usable for more people, not just me.

Thanks!

**Comment by robertbasic** [comment]
Here's the current readme: https://github.com/robertbasic/vim-hugo-helper/blob/3ed049e6333c55cbd85596243f1642df4d81c340/README.md
